version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - mon_reseau
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
  mon-app-producer:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mon_reseau
    depends_on:
      - rabbitmq

networks:
  mon_reseau:
    external: true